addSbtPlugin("org.scalameta"    % "sbt-scalafmt"   % "2.5.2")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"   % "0.12.1")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"    % "0.6.4")
addSbtPlugin("org.scalameta"    % "sbt-mdoc"       % "2.6.1")
addSbtPlugin("com.github.sbt"   % "sbt-ci-release" % "1.6.1")
